# # Form implementation generated from reading ui file 'login.ui'
# #
# # Created by: PyQt6 UI code generator 6.8.0
# #
# # WARNING: Any manual changes made to this file will be lost when pyuic6 is
# # run again.  Do not edit this file unless you know what you are doing.


# from PyQt6 import QtCore, QtGui, QtWidgets
# from PyQt6.QtGui import QPixmap,QIcon
# from PyQt6.QtCore import Qt,QSize

# class Ui_Form(object):
#     def setupUi(self, Form):
#         Form.setObjectName("Form")
#         Form.resize(935, 633)
        
#         self.lineEdit = QtWidgets.QLineEdit(parent=Form)
#         self.lineEdit.setGeometry(QtCore.QRect(310, 130, 361, 51))
#         self.lineEdit.setStyleSheet("QLineEdit{\n"
# "padding:10px;\n"
# "border:1px solid;\n"
# "border-radius:8px;\n"
# "color:black;\n"
# "}")
#         self.lineEdit.setObjectName("lineEdit")
#         self.lineEdit_2 = QtWidgets.QLineEdit(parent=Form)
#         self.lineEdit_2.setGeometry(QtCore.QRect(310, 200, 361, 51))
#         self.lineEdit_2.setStyleSheet("QLineEdit{\n"
# "padding:10px;\n"
# "border:1px solid;\n"
# "border-radius:8px;\n"
# "color:black;\n"
# "}")
#         self.lineEdit_2.setObjectName("lineEdit_2")
#         self.lineEdit_3 = QtWidgets.QLineEdit(parent=Form)
#         self.lineEdit_3.setGeometry(QtCore.QRect(310, 280, 361, 51))
#         self.lineEdit_3.setStyleSheet("QLineEdit{\n"
# "padding:10px;\n"
# "border:1px solid;\n"
# "border-radius:8px;\n"
# "color:black;\n"
# "}")
#         self.lineEdit_3.setObjectName("lineEdit_3")
#         self.lineEdit_4 = QtWidgets.QLineEdit(parent=Form)
#         self.lineEdit_4.setGeometry(QtCore.QRect(310, 360, 361, 51))
#         self.lineEdit_4.setStyleSheet("QLineEdit{\n"
# "padding:10px;\n"
# "border:1px solid;\n"
# "border-radius:8px;\n"
# "color:black;\n"
# "}")
#         self.lineEdit_4.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
#         self.lineEdit_4.setObjectName("lineEdit_4")
#         self.pushButton = QtWidgets.QPushButton(parent=Form)
#         self.pushButton.setGeometry(QtCore.QRect(390, 430, 181, 41))
#         self.pushButton.setStyleSheet("QPushButton {\n"
# "    font-size:14px;\n"
# "    font-weight:bold;\n"
# "color:orange;\n"
# "background-color:#f7f1ef;\n"
# "border:1px solid;\n"
# "border-radius:10px;\n"
# "}\n"
# "QPushButton::hover{\n"
# "background-color:#f3e3dd;\n"
# "}")
#         self.pushButton.setObjectName("pushButton")

#         self.retranslateUi(Form)
#         QtCore.QMetaObject.connectSlotsByName(Form)

#     def retranslateUi(self, Form):
#         _translate = QtCore.QCoreApplication.translate
#         Form.setWindowTitle(_translate("Form", "Form"))
#         self.lineEdit.setText(_translate("Form", "Enter your first name"))
#         self.lineEdit_2.setText(_translate("Form", "Enter your last name"))
#         self.lineEdit_3.setText(_translate("Form", "Enter your email address"))
#         self.lineEdit_4.setText(_translate("Form", "Enter your password"))
#         self.pushButton.setText(_translate("Form", "Sign Up"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     Form = QtWidgets.QWidget()
#     ui = Ui_Form()
#     ui.setupUi(Form)
#     Form.show()
#     sys.exit(app.exec())


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtGui import QPixmap, QIcon
from PyQt6.QtCore import Qt, QSize


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(935, 633)

        # Set background image for the Form
        Form.setStyleSheet("QWidget#Form {"
                           "background-image: url('assets/bgLog.jpeg');"
                           "background-position: center;"
                           "background-repeat: no-repeat;"
                           "background-size: cover;"
                           "}")

        self.lineEdit = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit.setGeometry(QtCore.QRect(310, 130, 361, 51))
        self.lineEdit.setStyleSheet("QLineEdit{\n"
                                    "padding:10px;\n"
                                    "border:1px solid;\n"
                                    "border-radius:8px;\n"
                                    "color:black;\n"
                                    "}")
        self.lineEdit.setObjectName("lineEdit")

        self.lineEdit_2 = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(310, 200, 361, 51))
        self.lineEdit_2.setStyleSheet("QLineEdit{\n"
                                      "padding:10px;\n"
                                      "border:1px solid;\n"
                                      "border-radius:8px;\n"
                                      "color:black;\n"
                                      "}")
        self.lineEdit_2.setObjectName("lineEdit_2")

        self.lineEdit_3 = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit_3.setGeometry(QtCore.QRect(310, 280, 361, 51))
        self.lineEdit_3.setStyleSheet("QLineEdit{\n"
                                      "padding:10px;\n"
                                      "border:1px solid;\n"
                                      "border-radius:8px;\n"
                                      "color:black;\n"
                                      "}")
        self.lineEdit_3.setObjectName("lineEdit_3")

        self.lineEdit_4 = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit_4.setGeometry(QtCore.QRect(310, 360, 361, 51))
        self.lineEdit_4.setStyleSheet("QLineEdit{\n"
                                      "padding:10px;\n"
                                      "border:1px solid;\n"
                                      "border-radius:8px;\n"
                                      "color:black;\n"
                                      "}")
        self.lineEdit_4.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_4.setObjectName("lineEdit_4")

        self.pushButton = QtWidgets.QPushButton(parent=Form)
        self.pushButton.setGeometry(QtCore.QRect(390, 430, 181, 41))
        self.pushButton.setStyleSheet("QPushButton {\n"
                                      "    font-size:14px;\n"
                                      "    font-weight:bold;\n"
                                      "color:orange;\n"
                                      "background-color:#f7f1ef;\n"
                                      "border:1px solid;\n"
                                      "border-radius:10px;\n"
                                      "}\n"
                                      "QPushButton::hover{\n"
                                      "background-color:#f3e3dd;\n"
                                      "}")
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lineEdit.setText(_translate("Form", "Enter your first name"))
        self.lineEdit_2.setText(_translate("Form", "Enter your last name"))
        self.lineEdit_3.setText(_translate("Form", "Enter your email address"))
        self.lineEdit_4.setText(_translate("Form", "Enter your password"))
        self.pushButton.setText(_translate("Form", "Sign Up"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
