"""isloggedin flag added on user table

Revision ID: 6b1678bc9009
Revises: f77c9abd06b9
Create Date: 2025-02-01 18:50:05.524061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b1678bc9009'
down_revision: Union[str, None] = 'f77c9abd06b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('isLoggedIn', sa.Boolean(), nullable=True))
    op.drop_column('users', 'accessToken')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('accessToken', sa.VARCHAR(length=255), nullable=True))
    op.drop_column('users', 'isLoggedIn')
    # ### end Alembic commands ###
