"""access token column is added on user table

Revision ID: f77c9abd06b9
Revises: 6f0ab43f8cdb
Create Date: 2025-02-01 18:11:14.728384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f77c9abd06b9'
down_revision: Union[str, None] = '6f0ab43f8cdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('accessToken', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'accessToken')
    # ### end Alembic commands ###
